BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 3
  LR: 1e-3
  MODEL_FILE_NAME: AFRL_AFRL_UBFC_tscan.pth
  DATA:
    FS: 30
    DATASET: AFRL
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/AFRL"          # Raw dataset path, need to be updated - this value is unused, and it overridden by hardcoded values in AFRLLoader
    CACHED_PATH: "/gscratch/ubicomp/girishvn/projects/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS :
      DATA_TYPE: ['Normalized','Standardized']
      LABEL_TYPE: Normalized
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY: 180
      CROP_FACE: False
      LARGE_FACE_BOX: False
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: AFRL
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/AFRL"          # Raw dataset path, need to be updated - this value is unused, and it overridden by hardcoded values in AFRLLoader
    CACHED_PATH: "/gscratch/ubicomp/girishvn/projects/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY: 180
      CROP_FACE: False
      LARGE_FACE_BOX: False
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC/RawData"          # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/girishvn/projects/rppg_datasets/PreprocessedData/"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY: 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  MODEL_PATH: "./PreTrainedModels/AFRL_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized_Large_boxFalse_Large_size1.5_Dyamic_DetFalse_det_len180/AFRL_AFRL_UBFC_tscan.pth_Epoch8.pth"
  #MODEL_PATH:   "./PreTrainedModels/AFRL_SizeW72_SizeH72_ClipLength180_DataTypeNormalized_Standardized_LabelTypeNormalized_Large_boxFalse_Large_size1.5_Dyamic_DetFalse_det_len180/AFRL_AFRL_UBFC_tscan.pth_Epoch9.pth"
                    # if TRAIN_OR_TEST:"train_and_test", should be "" or anything, it will use currently trained model.
                    # if TRAIN_OR_TEST:"only_test", should be "path"
