BASE: ['']
DATA:
  CACHED_PATH: preprocess
  DATASET: SYNTHETICS
  DO_PREPROCESS: True
  DATA_FORMAT: NDCHW
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: False
    LARGE_FACE_BOX: False
    FACE_DETECT: False
    H: 36
    W: 36
  VALID_SUBJ: 3
DEVICE: cuda:0
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  MODEL_DIR: store_model
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 0.0001
  MODEL_FILE_NAME: tscan.pth